
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - cd srctweb/
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll build --trace -d '../build'
only:
    - master
  artifacts:
    paths:
    - build
prod_deploy:
  stage: build
  script:
    - cd /srv/srctweb-jekyll/ && bundle exec jekyll build --trace -d '/srv/srctweb-jekyll/_site'
  only:
    - master
  tags:
    - master
    - builds