image: ruby:2.3

stages:
  - build
  - deploy

variables:
  JEKYLL_ENV: production

before_script:
  - cd srctweb/
  - gem install bundler
  - bundle install


build:
  stage: build
  before_script:
  - cd srctweb/
  - gem install bundler
  - bundle install
  script:
  - bundle exec jekyll build --trace -d '../build'
  artifacts:
    paths:
    - build
    
deploy_staging:
  stage: deploy
  image: ubuntu:16.04
  script:
  - echo 'Deploy bot awayyy';
  environment:
    name: staging
    url: https://srct.gmu.io

deploy_production:
  stage: deploy
  image: ubuntu:16.04
  script: echo "Deploy bot awayyyyy"
  environment:
    name: production
    url: https://srct.gmu.edu
  when: manual
  only:
    - master

