
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - cd srctweb/
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll build --trace -d '../build'
  artifacts:
    paths:
    - build
prod_deploy:
  stage: deploy
  script:
    - export GIT_SSL_NO_VERIFY=true && cd /srv/srctweb-jekyll/source && git stash save --keep-index && git stash drop && return true
    - export GIT_SSL_NO_VERIFY=true && cd /srv/srctweb-jekyll/source  && git pull && cd ../
    - cp -rf /srv/srctweb-jekyll/source/* /srv/srctweb-jekyll/
    - cd /srv/srctweb-jekyll/ && bundle exec jekyll build --trace -d '/srv/srctweb-jekyll/_site'
  only:
    - master
  tags:
    - master
    - builds