<<<<<<< HEAD
image: python:2

pages:
  script:
  - pip install -r requirements.txt
  - python srctweb/srctweb.py build
  - mv srctweb/website/build/ public/
  artifacts:
    paths:
    - public/
  only:
  - master

=======
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - cd srctweb/
  - bundle install

build:
  stage: build
  script:
  - bundle exec jekyll build --trace -d '../build'
  artifacts:
    paths:
    - build
>>>>>>> origin/1.0-jekyll-rewrite
