stages:
  - build
  - deploy

variables:
  JEKYLL_ENV: production

build:
  image: ruby:2.3
  stage: build
  script:
    - cd srctweb/
    - bundle install
    - bundle exec jekyll build --trace -d '../build'
  artifacts:
    paths:
      - build
    
deploy_staging:
  image: alpine
  stage: deploy
  script:
    - echo 'Deploy bot awayyy';
  environment:
    name: staging
    url: https://srct.gmu.io

deploy_production:
  image: alpine
  stage: deploy
  script:
    - echo "Deploy bot awayyyyy"
  environment:
    name: production
    url: https://srct.gmu.edu
  when: manual
  only:
    - master

