# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/octopress
image: python:2

pages:
  script:
  - pip install -r requirements.txt
  - python srctweb/srctweb.py build
  artifacts:
    paths:
    - srctweb/website/build/
  only:
  - master

