image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - cd srctweb/
  - bundle install

build:
  stage: build
  script:
  - cd srctweb/
  - bundle exec jekyll build -d '../build'
  artifacts:
    paths:
    - build
