# Site settings
locale                   : "en-US"
title                    : "SRCT"
email                    : "srct@gmu.edu"
description              : "Mason SRCT is a student organization at George Mason University that establishes and maintains systems which provide specific services for Mason's community."
author                   : "Mason SRCT"

# the subpath of your site, e.g. /blog
baseurl                  : ""
# the base hostname & protocol for your site, e.g. http://example.com
url                      : "https://srct.gmu.edu"


# Social Sharing
twitter:
  username               : "masonsrct"
github:
  username               : "masonsrct"
facebook:
  username               : "masonsrct"
  app_id                 :
  publisher              :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      jumbotron: false
